-- MyEvents connected foundation. Run on a dedicated staging Supabase project.
begin;

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  tenant_id uuid not null unique default gen_random_uuid(),
  first_name text not null check (char_length(first_name) <= 100),
  last_name text not null check (char_length(last_name) <= 100),
  created_at timestamptz not null default now()
);

create function public.create_user_profile() returns trigger
language plpgsql security definer set search_path = '' as $$
begin
  insert into public.profiles (id, first_name, last_name)
  values (new.id, left(coalesce(new.raw_user_meta_data->>'first_name', ''), 100), left(coalesce(new.raw_user_meta_data->>'last_name', ''), 100));
  -- tenant_id is generated by PostgreSQL, never taken from user-editable metadata.
  return new;
end;
$$;
revoke all on function public.create_user_profile() from public, anon, authenticated;
create trigger myevents_auth_user_created after insert on auth.users
for each row execute function public.create_user_profile();

create table public.workspaces (
  id uuid primary key default gen_random_uuid(),
  tenant_id uuid not null unique references public.profiles(tenant_id),
  name text not null check (char_length(name) between 1 and 100),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (id, tenant_id)
);

create table public.events (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null,
  tenant_id uuid not null,
  created_by uuid not null references public.profiles(id),
  type text not null check (char_length(type) between 1 and 80),
  name text not null check (char_length(btrim(name)) between 1 and 100),
  start_at timestamptz not null,
  end_at timestamptz,
  timezone text not null,
  default_language text not null check (char_length(default_language) between 2 and 35),
  primary_location text check (char_length(primary_location) <= 500),
  estimated_guest_count integer check (estimated_guest_count >= 0),
  lifecycle_status text not null default 'draft' check (lifecycle_status in ('draft', 'published', 'archived')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  deleted_at timestamptz,
  foreign key (workspace_id, tenant_id) references public.workspaces(id, tenant_id),
  check (end_at is null or end_at >= start_at)
);
create index events_tenant_workspace_active on public.events(tenant_id, workspace_id) where deleted_at is null;

create function public.validate_event_timezone() returns trigger
language plpgsql set search_path = '' as $$
begin
  if not exists (select 1 from pg_catalog.pg_timezone_names where name = new.timezone) then
    raise exception 'Invalid event timezone';
  end if;
  return new;
end;
$$;
create trigger myevents_event_timezone before insert or update on public.events
for each row execute function public.validate_event_timezone();
revoke all on function public.validate_event_timezone() from public, anon, authenticated;

alter table public.profiles enable row level security;
alter table public.workspaces enable row level security;
alter table public.events enable row level security;

revoke all on public.profiles, public.workspaces, public.events from anon, authenticated;
grant select on public.profiles to authenticated;
grant select, insert on public.workspaces, public.events to authenticated;
grant update (name, updated_at) on public.workspaces to authenticated;
grant update (name, start_at, end_at, timezone, default_language, primary_location, estimated_guest_count, updated_at, deleted_at) on public.events to authenticated;

create policy profiles_read_own on public.profiles for select to authenticated using (id = (select auth.uid()));
create policy workspaces_read_own on public.workspaces for select to authenticated using (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));
create policy workspaces_insert_own on public.workspaces for insert to authenticated with check (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));
create policy workspaces_update_own on public.workspaces for update to authenticated using (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid()))) with check (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));
create policy events_read_own on public.events for select to authenticated using (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));
create policy events_insert_draft on public.events for insert to authenticated with check (created_by = (select auth.uid()) and lifecycle_status = 'draft' and deleted_at is null and tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));
create policy events_update_own on public.events for update to authenticated using (deleted_at is null and tenant_id in (select tenant_id from public.profiles where id = (select auth.uid()))) with check (tenant_id in (select tenant_id from public.profiles where id = (select auth.uid())));

-- No DELETE grants, no anonymous reads, no authenticated mutation of identity,
-- ownership, tenant IDs or publication state. Publication gets its own milestone.
commit;
